document.documentElement.classList.add('js');
const cover=document.getElementById('cover'),main=document.getElementById('invitation');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const musicButton=document.getElementById('music');let audioContext,musicTimer,musicOn=false;
function playPhrase(){if(!audioContext)return;const notes=[261.63,329.63,392,523.25,493.88,392,329.63,293.66,349.23,440,523.25,587.33,523.25,440,349.23,392];const t=audioContext.currentTime;notes.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,t+i*.65);g.gain.linearRampToValueAtTime(.045,t+i*.65+.03);g.gain.exponentialRampToValueAtTime(.0001,t+i*.65+1.5);o.connect(g);g.connect(audioContext.destination);o.start(t+i*.65);o.stop(t+i*.65+1.6)})}
async function toggleMusic(){try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(musicOn){clearInterval(musicTimer);await audioContext.suspend();musicOn=false}else{await audioContext.resume();playPhrase();musicTimer=setInterval(playPhrase,11000);musicOn=true}musicButton.setAttribute('aria-pressed',String(musicOn));musicButton.setAttribute('aria-label',musicOn?'Pausar música':'Activar música')}catch{musicButton.hidden=true}}
musicButton.onclick=toggleMusic;
document.getElementById('enter').onclick=()=>{cover.classList.add('open');main.inert=false;document.body.classList.remove('closed');musicButton.hidden=false;setTimeout(()=>{cover.hidden=true;document.querySelector('h1').tabIndex=-1;document.querySelector('h1').focus({preventScroll:true})},reduced?0:1200)};
function tick(){const n=Math.max(0,new Date('2026-10-15T00:00:00-05:00')-Date.now());[Math.floor(n/86400000),Math.floor(n/3600000)%24,Math.floor(n/60000)%60,Math.floor(n/1000)%60].forEach((v,i)=>document.getElementById(['days','hours','minutes','seconds'][i]).textContent=String(v).padStart(2,'0'))}tick();setInterval(tick,1000);
function confirmationUrl(name,attendance){const response=attendance==='yes'?'Sí, allí estaré. Confirmo mi asistencia.':'Lo siento, no podré asistir.';return 'https://wa.me/51902136143?text='+encodeURIComponent(`¡Hola! Soy ${name}. Respondo a la invitación de los XV años de Daniela, el 15 de octubre de 2026. ${response}`)}
document.getElementById('rsvpForm').onsubmit=e=>{e.preventDefault();const name=document.getElementById('guest').value.trim();if(!name){document.getElementById('guest').setCustomValidity('Escribe tu nombre y apellidos.');document.getElementById('guest').reportValidity();return}const attendance=new FormData(e.target).get('attendance');if(!attendance)return;const url=confirmationUrl(name,attendance);const fallback=document.getElementById('waFallback');fallback.href=url;fallback.hidden=false;window.open(url,'_blank','noopener,noreferrer')};document.getElementById('guest').oninput=e=>e.target.setCustomValidity('');
const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('[data-slide]')];let current=0,paused=reduced,carouselTimer;
function showSlide(i){current=(i+slides.length)%slides.length;slides.forEach((s,n)=>{s.classList.toggle('active',n===current);s.setAttribute('aria-hidden',String(n!==current))});dots.forEach((s,n)=>s.setAttribute('aria-pressed',String(n===current)))}
function restart(){clearInterval(carouselTimer);if(!paused)carouselTimer=setInterval(()=>{if(!document.hidden)showSlide(current+1)},4500)}
document.querySelector('.carousel-prev').onclick=()=>{showSlide(current-1);restart()};document.querySelector('.carousel-next').onclick=()=>{showSlide(current+1);restart()};dots.forEach(d=>d.onclick=()=>{showSlide(Number(d.dataset.slide));restart()});const pause=document.querySelector('.carousel-pause');function updatePause(){pause.textContent=paused?'▶':'Ⅱ';pause.setAttribute('aria-label',paused?'Reproducir carrusel':'Pausar carrusel')}pause.onclick=()=>{paused=!paused;updatePause();restart()};updatePause();restart();let startX;const slider=document.querySelector('.slides');slider.addEventListener('touchstart',e=>startX=e.changedTouches[0].clientX,{passive:true});slider.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-startX;if(Math.abs(delta)>40){showSlide(current+(delta<0?1:-1));restart()}},{passive:true});slider.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();showSlide(current+(e.key==='ArrowRight'?1:-1));restart()}};
const dialog=document.getElementById('giftDialog');document.getElementById('giftDetails').onclick=()=>dialog.showModal();dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};
